name: Docker Hub Image Monitor

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次
  workflow_dispatch:  # 支持手动触发

env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # 企业微信机器人webhook地址
  EMAIL_TO: ${{ secrets.EMAIL_TO }}        # 接收通知的邮箱地址
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}    # 发送通知的邮箱地址
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # 邮箱密码

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Check Docker Hub updates
        run: |
          python scripts/check_updates.py
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_updated/ logs/
          git commit -m "Update last_updated timestamps" || echo "No changes to commit"
          git push
        